In [1]:
import cv2 as cv
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
def mean_average_precision(pred, rank=10):
    n_vals = min(rank, pred.shape[1])
    corr_cum_sum = np.cumsum(pred, axis=1)
    vals_num_range = np.repeat(
        np.arange(1, n_vals + 1)[None, ...], repeats=pred.shape[0], axis=0)
    precisions_at_k = (corr_cum_sum / vals_num_range) * pred
    average_precisions_at_k = (np.sum(precisions_at_k, axis=1) /
                               np.sum(pred, axis=1))
    return np.mean(average_precisions_at_k)

In [3]:
gallery_emb = np.load('_emb_cache.npy')[:5]
dist_mat = euclidean_distances(gallery_emb)
dist_mat

array([[0.        , 0.07587937, 0.10652778, 0.13014638, 0.14777254],
       [0.07587937, 0.        , 0.04717795, 0.07598841, 0.10892958],
       [0.10652778, 0.04717795, 0.        , 0.09023546, 0.13944326],
       [0.13014638, 0.07598841, 0.09023546, 0.        , 0.06821314],
       [0.14777254, 0.10892958, 0.13944326, 0.06821314, 0.        ]],
      dtype=float32)

In [11]:
order_indices = np.argsort(dist_mat, axis=1)[:-1,1:]
order_indices

array([[1, 2, 3, 4],
       [2, 0, 3, 4],
       [1, 3, 0, 4],
       [4, 1, 2, 0]], dtype=int64)

In [15]:
dist_mat[order_indices]

array([[[0.07587937, 0.        , 0.04717795, 0.07598841, 0.10892958],
        [0.10652778, 0.04717795, 0.        , 0.09023546, 0.13944326],
        [0.13014638, 0.07598841, 0.09023546, 0.        , 0.06821314],
        [0.14777254, 0.10892958, 0.13944326, 0.06821314, 0.        ]],

       [[0.10652778, 0.04717795, 0.        , 0.09023546, 0.13944326],
        [0.        , 0.07587937, 0.10652778, 0.13014638, 0.14777254],
        [0.13014638, 0.07598841, 0.09023546, 0.        , 0.06821314],
        [0.14777254, 0.10892958, 0.13944326, 0.06821314, 0.        ]],

       [[0.07587937, 0.        , 0.04717795, 0.07598841, 0.10892958],
        [0.13014638, 0.07598841, 0.09023546, 0.        , 0.06821314],
        [0.        , 0.07587937, 0.10652778, 0.13014638, 0.14777254],
        [0.14777254, 0.10892958, 0.13944326, 0.06821314, 0.        ]],

       [[0.14777254, 0.10892958, 0.13944326, 0.06821314, 0.        ],
        [0.07587937, 0.        , 0.04717795, 0.07598841, 0.10892958],
        [0.106

In [57]:
a = np.random.randint(0, 10, size=(4, 5))
a

array([[9, 4, 6, 6, 6],
       [9, 2, 5, 0, 7],
       [4, 2, 5, 2, 0],
       [8, 9, 3, 1, 5]])

In [90]:
idx = np.argsort(a, axis=1)

In [100]:
gt = np.array([3, 9])
gt

array([3, 9])

In [101]:
np.any(a[..., None] == gt, axis=2)

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True, False, False]])

array([ True,  True,  True, False,  True,  True, False])