In [11]:
import numpy as np
from scipy.optimize import linear_sum_assignment

cost = np.array([
    [0, 1, 2],
    [1, 0, 2],
    [1, 2, 0]
])
cost

array([[0, 1, 2],
       [1, 0, 2],
       [1, 2, 0]])

In [12]:
row_ind, col_ind = linear_sum_assignment(cost)
row_ind, col_ind

(array([0, 1, 2]), array([0, 1, 2], dtype=int64))

In [14]:
row_ind

array([0, 1, 2])